version: "3.2"
services:
  pymei:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./drafts:/opt/drafts"
    image: ddmal/pymei:latest
    command: bash -c "tail -f /dev/null"
